name: Build & Test

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    strategy:
      matrix:
        platform-arch: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform-arch }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Install dependencies
        run: make build

      - name: Check await binary
        run: ./await -V || exit 1

      - name: Test
        run: make test
