name: Make release

on:
  push:
    tags:
    - '*'

jobs:
  create_release:
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create.outputs.upload_url }}
    steps:
      - uses: actions/checkout@v3
      - name: Create Release
        id: create
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false

  upload_binaries:
    needs: create_release
    strategy:
      matrix:
        platform-arch: [ubuntu, macos]
    runs-on: ${{ matrix.platform-arch }}-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Make release
        run: PLATFORM=${{ matrix.platform-arch }} make rel

      - name: Upload amd64 binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: ./await-${{ matrix.platform-arch }}-amd64
          asset_name: await-${{ matrix.platform-arch }}-amd64
          asset_content_type: application/octet-stream

      - name: Upload arm64 binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: ./await-${{ matrix.platform-arch }}-arm64
          asset_name: await-${{ matrix.platform-arch }}-arm64
          asset_content_type: application/octet-stream
